[package]
name = "vterm"
version = "0.1.0"
authors = ["roblabla <robinlambertz+dev@gmail.com>"]

[dependencies]
libc = "*"

[dependencies.libvterm-sys]
git = "https://github.com/roblabla/libvterm-sys.git"
